version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8001:8000
    volumes:
      - ./:/usr/src/app:ro
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_NAME=trio
      - PASSWORD=DADDYCHILL
      - DATABASE_PORT=5432
      - SECRET_KEY=AKKADBAKKADBAMBEBOASSINABBEPURESAW
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    command: uvicorn server.main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=DADDYCHILL
      - POSTGRES_DB=trio

    volumes:
      - postgres-db:/var/lib/postgresql/data


volumes:
  postgres-db:
